package com.kblaney.nhl.draft.ui;

import com.kblaney.assertions.ArgAssert;
import com.kblaney.nhl.draft.DraftPositionInFirstRoundValidator;
import com.kblaney.nhl.draft.IntOrStringValidator;
import com.kblaney.nhl.draft.NumPooleesValidator;
import com.kblaney.nhl.draft.Poolee;
import com.kblaney.nhl.draft.PooleeNameValidator;
import java.awt.Frame;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 * A dialog that adds a poolee to a draft.
 */
@SuppressWarnings("serial")
final class AddPooleeDialog extends JDialog
{
  private static final boolean IS_MODAL = true;
  private final PooleeNameValidator nameValidator = new PooleeNameValidator();
  private final IntOrStringValidator draftPositionInFirstRoundValidator;
  private boolean wasOkPressed;
  private Poolee poolee;
  private int draftPositionInFirstRound;

  /**
   * Constructs a new instance of AddPooleeDialog that has a specified
   * parent frame for a draft that has a specified number of poolees.
   *
   * @param parent the parent frame, which can't be null
   * @param numPoolees the number of poolees in the draft, which must be valid
   */
  public AddPooleeDialog(final Frame parent, final int numPoolees)
  {
    super(parent, AddPooleeDialog.IS_MODAL);
    ArgAssert.assertNotNull(parent, "parent");
    ArgAssert.assertTrue(new NumPooleesValidator().isValid(numPoolees), "numPoolees is valid");

    draftPositionInFirstRoundValidator =
          new DraftPositionInFirstRoundValidator(numPoolees);

    initComponents();

    getRootPane().setDefaultButton(okButton);
    setLocationRelativeTo(parent);
  }

  /**
   * Determines whether OK was pressed to close this dialog.
   *
   * @return true if OK was pressed to close this dialog; false otherwise
   */
  public boolean wasOkPressed()
  {
    return wasOkPressed;
  }

  /**
   * Gets the poolee entered on this dialog, or null if the user canceled this
   * dialog.
   *
   * @return the poolee entered on this dialog, or null if the user canceled
   * this dialog
   */
  public Poolee getPoolee()
  {
    return poolee;
  }

  /**
   * Gets the draft position in the first round entered on this dialog, or
   * 0 if the user canceled this dialog.
   *
   * @return the draft position in the first round entered on this dialog, or
   * 0 if the user canceled this dialog
   */
  public int getDraftPositionInFirstRound()
  {
    return draftPositionInFirstRound;
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
   private void initComponents()//GEN-BEGIN:initComponents
   {
      java.awt.GridBagConstraints gridBagConstraints;

      firstNameLabel = new javax.swing.JLabel();
      lastNameLabel = new javax.swing.JLabel();
      draftPositionInFirstRoundLabel = new javax.swing.JLabel();
      firstNameTextField = new javax.swing.JTextField();
      lastNameTextField = new javax.swing.JTextField();
      draftPositionInFirstRoundTextField = new javax.swing.JTextField();
      buttonPanel = new javax.swing.JPanel();
      okButton = new javax.swing.JButton();

      getContentPane().setLayout(new java.awt.GridBagLayout());

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("Add new poolee");
      firstNameLabel.setText("First name:  ");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
      gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
      getContentPane().add(firstNameLabel, gridBagConstraints);

      lastNameLabel.setText("Last name:  ");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 1;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
      gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
      getContentPane().add(lastNameLabel, gridBagConstraints);

      draftPositionInFirstRoundLabel.setText("Draft position in first round:  ");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 2;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
      gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
      getContentPane().add(draftPositionInFirstRoundLabel, gridBagConstraints);

      firstNameTextField.setColumns(25);
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
      gridBagConstraints.weightx = 1.0;
      getContentPane().add(firstNameTextField, gridBagConstraints);

      lastNameTextField.setColumns(25);
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 1;
      gridBagConstraints.gridy = 1;
      gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
      gridBagConstraints.weightx = 1.0;
      getContentPane().add(lastNameTextField, gridBagConstraints);

      draftPositionInFirstRoundTextField.setColumns(25);
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 1;
      gridBagConstraints.gridy = 2;
      gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
      gridBagConstraints.weightx = 1.0;
      getContentPane().add(draftPositionInFirstRoundTextField, gridBagConstraints);

      okButton.setText("OK");
      okButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent event)
         {
            okActionPerformed(event);
         }
      });

      buttonPanel.add(okButton);

      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 1;
      gridBagConstraints.gridy = 3;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
      getContentPane().add(buttonPanel, gridBagConstraints);

      pack();
   }//GEN-END:initComponents

   private void okActionPerformed(java.awt.event.ActionEvent event)//GEN-FIRST:event_okActionPerformed
   {//GEN-HEADEREND:event_okActionPerformed
     final String firstName = getFirstName();
     final String lastName = getLastName();
     final String draftPositionInFirstRoundString =
           getDraftPositionInFirstRoundString();

     if (isValid(firstName))
     {
       if (isValid(lastName))
       {
         if (draftPositionInFirstRoundValidator.isValid(
               draftPositionInFirstRoundString))
         {
           draftPositionInFirstRound = Integer.parseInt(
                 draftPositionInFirstRoundString);
           poolee = new Poolee(firstName, lastName);
           wasOkPressed = true;
           dispose();
           setVisible(false);
         }
         else
         {
           JOptionPane.showMessageDialog(this,
                 draftPositionInFirstRoundString + " is not a valid " +
                 "draft position");
         }
       }
       else
       {
         JOptionPane.showMessageDialog(this,
               lastName + " is not a valid last name");
       }
     }
     else
     {
       JOptionPane.showMessageDialog(this,
             firstName + " is not a valid first name");
     }
   }//GEN-LAST:event_okActionPerformed

  private boolean isValid(final String name)
  {
    return nameValidator.isValid(name);
  }

  private String getFirstName()
  {
    return trimmedTextIn(firstNameTextField);
  }

  private String trimmedTextIn(final JTextField textField)
  {
    return textField.getText().trim();
  }

  private String getLastName()
  {
    return trimmedTextIn(lastNameTextField);
  }

  private String getDraftPositionInFirstRoundString()
  {
    return trimmedTextIn(draftPositionInFirstRoundTextField);
  }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JPanel buttonPanel;
   private javax.swing.JLabel draftPositionInFirstRoundLabel;
   private javax.swing.JTextField draftPositionInFirstRoundTextField;
   private javax.swing.JLabel firstNameLabel;
   private javax.swing.JTextField firstNameTextField;
   private javax.swing.JLabel lastNameLabel;
   private javax.swing.JTextField lastNameTextField;
   private javax.swing.JButton okButton;
   // End of variables declaration//GEN-END:variables
}
