package com.kblaney.nhl.draft.ui;

import com.google.common.collect.Lists;
import com.kblaney.assertions.ArgAssert;
import com.kblaney.nhl.draft.Poolee;
import java.awt.Frame;
import java.util.List;
import javax.swing.JDialog;

@SuppressWarnings("serial")
final class ShowPooleesDialog extends JDialog
{
  private final List<Poolee> firstRoundDraftOrder;
  private static final boolean IS_MODAL = true;

  public ShowPooleesDialog(final Frame parent,
        final List<Poolee> firstRoundDraftOrder)
  {
    super(parent, IS_MODAL);
    ArgAssert.assertNotNull(parent, "parent");
    ArgAssert.assertNotNull(firstRoundDraftOrder, "firstRoundDraftOrder");

    // Store a defensive copy.
    //
    this.firstRoundDraftOrder = Lists.newArrayList(firstRoundDraftOrder);

    initComponents();

    getRootPane().setDefaultButton(okButton);
    setLocationRelativeTo(parent);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
   @SuppressWarnings("unused")
   private void initComponents()//GEN-BEGIN:initComponents
   {
      java.awt.GridBagConstraints gridBagConstraints;

      titleLabel = new javax.swing.JLabel();
      pooleeScrollPane = new javax.swing.JScrollPane();
      pooleeTable = new javax.swing.JTable();
      buttonPanel = new javax.swing.JPanel();
      okButton = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("Poolees");
      titleLabel.setFont(new java.awt.Font("Tahoma", 1, 18));
      titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      titleLabel.setText("Poolees");
      getContentPane().add(titleLabel, java.awt.BorderLayout.NORTH);

      pooleeTable.setModel(new PooleeTableModel( this.firstRoundDraftOrder ));
      pooleeScrollPane.setViewportView(pooleeTable);

      getContentPane().add(pooleeScrollPane, java.awt.BorderLayout.CENTER);

      buttonPanel.setLayout(new java.awt.BorderLayout());

      okButton.setText("OK");
      okButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent event)
         {
            exitActionPerformed(event);
         }
      });

      buttonPanel.add(okButton, java.awt.BorderLayout.EAST);

      getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

      pack();
   }//GEN-END:initComponents

   private void exitActionPerformed(java.awt.event.ActionEvent event)//GEN-FIRST:event_exitActionPerformed
   {//GEN-HEADEREND:event_exitActionPerformed
     dispose();
     setVisible(false);
   }//GEN-LAST:event_exitActionPerformed

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JPanel buttonPanel;
   private javax.swing.JButton okButton;
   private javax.swing.JScrollPane pooleeScrollPane;
   private javax.swing.JTable pooleeTable;
   private javax.swing.JLabel titleLabel;
   // End of variables declaration//GEN-END:variables
}